### ISSUE TITLE
strandedness typos

### ISSUE THREAD

**Issue by gradientgardens** [Dowell-Lab/RNAseq-Flow#1]
bbduk_hisat2 process you are using reverseStranded and forwardStranded instead of reverse_stranded and forward_stranded

**Comment by magruca** [comment]
So you'll notice these parameters are initialized in nextflow.config and are consistent with those specified in the README. There was a typo however in the help specifying the arguments as `reverse_stranded` and `forwarded_stranded`. I have just pushed a correction to this. `reverse_stranded` and `forward_stranded` are initialized as variables in main.nf as parameters for the Nextflow log, so those have been left as is.

All of that is to say, if you were using `reverseStranded` and `forwardStranded` as arguments, the pipeline should be functioning as expected.
